package com.askade.ideallq.model.ideaManagement.roviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 20:13:45 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActivityDomainsROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ActivityDomainsROVOImpl() {
    }
}

