package com.askade.ideallq.model.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 20:07:30 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IdealQAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IdealQAMImpl() {
    }

    /**
     * Container's getter for Clients1.
     * @return Clients1
     */
    public ViewObjectImpl getClients() {
        return (ViewObjectImpl) findViewObject("Clients");
    }

    /**
     * Container's getter for IndividualClients1.
     * @return IndividualClients1
     */
    public ViewObjectImpl getIndividualClients() {
        return (ViewObjectImpl) findViewObject("IndividualClients");
    }

    /**
     * Container's getter for IndividualClientsVL1.
     * @return IndividualClientsVL1
     */
    public ViewLinkImpl getIndividualClientsVL() {
        return (ViewLinkImpl) findViewLink("IndividualClientsVL");
    }

    /**
     * Container's getter for ClientCategories1.
     * @return ClientCategories1
     */
    public ViewObjectImpl getClientCategories() {
        return (ViewObjectImpl) findViewObject("ClientCategories");
    }


    /**
     * Container's getter for Languages1.
     * @return Languages1
     */
    public ViewObjectImpl getLanguages() {
        return (ViewObjectImpl) findViewObject("Languages");
    }

    /**
     * Container's getter for ClientCredentials1.
     * @return ClientCredentials1
     */
    public ViewObjectImpl getClientCredentials() {
        return (ViewObjectImpl) findViewObject("ClientCredentials");
    }

    /**
     * Container's getter for ClientCredentialsVL1.
     * @return ClientCredentialsVL1
     */
    public ViewLinkImpl getClientCredentialsVL() {
        return (ViewLinkImpl) findViewLink("ClientCredentialsVL");
    }

    /**
     * Container's getter for ClientCategoriesTL1.
     * @return ClientCategoriesTL1
     */
    public ViewObjectImpl getClientCategoriesTL() {
        return (ViewObjectImpl) findViewObject("ClientCategoriesTL");
    }

    /**
     * Container's getter for ClientCategoriesTLVL1.
     * @return ClientCategoriesTLVL1
     */
    public ViewLinkImpl getClientCategoriesTLVL() {
        return (ViewLinkImpl) findViewLink("ClientCategoriesTLVL");
    }
}

