package com.askade.ideallq.model.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 20:07:30 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IdealQAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IdealQAMImpl() {
    }

    /**
     * Container's getter for Clients1.
     * @return Clients1
     */
    public ViewObjectImpl getClients() {
        return (ViewObjectImpl) findViewObject("Clients");
    }

    /**
     * Container's getter for IndividualClients1.
     * @return IndividualClients1
     */
    public ViewObjectImpl getIndividualClients() {
        return (ViewObjectImpl) findViewObject("IndividualClients");
    }

    /**
     * Container's getter for IndividualClientsVL1.
     * @return IndividualClientsVL1
     */
    public ViewLinkImpl getIndividualClientsVL() {
        return (ViewLinkImpl) findViewLink("IndividualClientsVL");
    }

    /**
     * Container's getter for ClientCategories1.
     * @return ClientCategories1
     */
    public ViewObjectImpl getClientCategories() {
        return (ViewObjectImpl) findViewObject("ClientCategories");
    }
}

