package com.askade.ideallq.model.ideaManagement.entities;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 20:09:04 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IdeaHeaderEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdeaId,
        RawDescription,
        Status,
        ClientId,
        OpeningDate,
        ClosingDate,
        ActivityDomainId,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        IdeaDetails;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return IdeaHeaderEOImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return IdeaHeaderEOImpl.AttributesEnum.firstIndex() + IdeaHeaderEOImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = IdeaHeaderEOImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDEAID = AttributesEnum.IdeaId.index();
    public static final int RAWDESCRIPTION = AttributesEnum.RawDescription.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CLIENTID = AttributesEnum.ClientId.index();
    public static final int OPENINGDATE = AttributesEnum.OpeningDate.index();
    public static final int CLOSINGDATE = AttributesEnum.ClosingDate.index();
    public static final int ACTIVITYDOMAINID = AttributesEnum.ActivityDomainId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int IDEADETAILS = AttributesEnum.IdeaDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IdeaHeaderEOImpl() {
    }

    /**
     * @param ideaId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal ideaId) {
        return new Key(new Object[] { ideaId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.askade.ideallq.model.ideaManagement.entities.IdeaHeaderEO");
    }


}

