package com.askade.ideallq.model.clientManagement.entities;

import com.askade.ideallq.model.overide.IdealQEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 26 09:52:09 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IndividualClientsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ClientId,
        Nume,
        Prenume,
        Cnp,
        BirthDate,
        CreationDate,
        CreatedBy,
        LastUpdateDate,
        LastUpdatedBy,
        Clients;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLIENTID = AttributesEnum.ClientId.index();
    public static final int NUME = AttributesEnum.Nume.index();
    public static final int PRENUME = AttributesEnum.Prenume.index();
    public static final int CNP = AttributesEnum.Cnp.index();
    public static final int BIRTHDATE = AttributesEnum.BirthDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CLIENTS = AttributesEnum.Clients.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IndividualClientsEOImpl() {
    }

    /**
     * @param clientId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal clientId) {
        return new Key(new Object[] { clientId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.askade.ideallq.model.clientManagement.entities.IndividualClientsEO");
    }


}

